version: '3'
services:
  web:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/app
  php:
    build: .
    user: root
    network_mode: "host"
    volumes:
      - ./web:/app
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: storj_dashboard
      MYSQL_USER: storj
      MYSQL_PASSWORD: storj