version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/app
  php:
    build: .
    user: root
    volumes:
      - ./web:/app
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: storj_dashboard
      MYSQL_USER: storj
      MYSQL_PASSWORD: storj
    ports:
      - "3306:3306"